# Lab 1. 

In [11]:
# 1.
b = [0 ,1, 2, 3, 4, 5, 6, 7, 8, 9]
a = np.array(b)
print(a)

# 2. 
b = [i for i in range(10)]
a = np.array(b)
print(a)

# 3.
b = [i for i in range(10) if i % 2 == 0]
c = np.array(b)
print(c)

# 4.
print(f'c.shape = {c.shape}')
print(f'c.ndim = {c.ndim}')
print(f'c.dtype = {c.dtype}')
print(f'c.size = {c.size}')
print(f'c.itemsize = {c.itemsize}')

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]
c.shape = (5,)
c.ndim = 1
c.dtype = int32
c.size = 5
c.itemsize = 4


# Lab 2.

In [28]:
# 1. 
a = np.array([23, 45, 67, 7, 2, 30, 34, 82])
print(f'a = np.array({a})')
print(f'최댓값 : {a.max()}')
print(f'최솟값 : {a.min()}')
print(f'평균 : {a.mean()}')

# 2.
b = np.random.randint(0, 99, 10)
print(f'b = {b}')
print(f'최댓값 : {b.max()}')
print(f'최솟값 : {b.min()}')
print(f'평균 : {b.mean()}')

# 3.
c = np.array([])
c = np.append(c, a)
c = np.append(c, b)
print(f'c = {c}')

a = np.array([23 45 67  7  2 30 34 82])
최댓값 : 82
최솟값 : 2
평균 : 36.25
b = [ 6 19 24 31 44 94 30 52 40 58]
최댓값 : 94
최솟값 : 6
평균 : 39.8
c = [23. 45. 67.  7.  2. 30. 34. 82.  6. 19. 24. 31. 44. 94. 30. 52. 40. 58.]


# Lab 3. 

In [36]:
# 1.
a = np.arange(1, 10).reshape(3, 3)
b = np.full((3, 3), 2)

print(a)
print(b)

# 2.
print(a + b)
print(a - b)
print(a * b)
print(a / b)
print(a @ b)
print(a ** 2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[2 2 2]
 [2 2 2]
 [2 2 2]]
[[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[-1  0  1]
 [ 2  3  4]
 [ 5  6  7]]
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
[[0.5 1.  1.5]
 [2.  2.5 3. ]
 [3.5 4.  4.5]]
[[12 12 12]
 [30 30 30]
 [48 48 48]]
[[ 1  4  9]
 [16 25 36]
 [49 64 81]]


# Lab 4.

In [40]:
# 1.
a1 = np.full((3, 3), 2)
print(a1)

# 2.
a2 = np.arange(1, 13)
print(a2)

# 3.
a3 = np.arange(0, 50, 3)
print(a3)

# 4.
a4 = np.linspace(0, 20, 5)
print(a4)

[[2 2 2]
 [2 2 2]
 [2 2 2]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]
[ 0  3  6  9 12 15 18 21 24 27 30 33 36 39 42 45 48]
[ 0.  5. 10. 15. 20.]


# Lab 5.

In [45]:
# 1.
a1 = np.arange(1, 13).reshape(2, 6)
print(f'a1 = {a1}')

# 2.
a2 = np.arange(1, 31).reshape(3, 10)
print(f'a2 = {a2}')

# 3.
a3 =a2.reshape(6, 5)
print(f'a3 = {a3}')

# 4.
a4 = np.transpose(a3)
print(f'a4 = {a4}')

a1 = [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
a2 = [[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]]
a3 = [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]
a4 = [[ 1  6 11 16 21 26]
 [ 2  7 12 17 22 27]
 [ 3  8 13 18 23 28]
 [ 4  9 14 19 24 29]
 [ 5 10 15 20 25 30]]


# Lab 6.

In [49]:
# 1.
a = np.random.randint(1, 100, 15).reshape(3, 5)
print(f'a = {a}')

# 2.
print(f'a의 열방향 최댓값 : {a.max(axis = 0)}')
print(f'a의 열방향 최솟값 : {a.min(axis = 0)}')
print(f'a의 열방향 평균 : {a.mean(axis = 0)}')

# 3.
print(f'a의 행방향 최댓값 : {a.max(axis = 1)}')
print(f'a의 행방향 최솟값 : {a.min(axis = 1)}')
print(f'a의 행방향 평균 : {a.mean(axis = 1)}')

a = [[69 73 99  1 88]
 [42 13 94 43 89]
 [96 46 80 13 34]]
a의 열방향 최댓값 : [96 73 99 43 89]
a의 열방향 최솟값 : [42 13 80  1 34]
a의 열방향 평균 : [69.         44.         91.         19.         70.33333333]
a의 행방향 최댓값 : [99 94 96]
a의 행방향 최솟값 : [ 1 13 13]
a의 행방향 평균 : [66.  56.2 53.8]


# Lab 7.

In [57]:
# 1.
a = np.arange(1, 11)
b = a[1:9:2]
print(f'a = {a}')
print(f'b = {b}')

# 2.
b = a[5:]
print(f'b = {b}')

c = a[6:]
print(f'c = {c}')

d = a[:3]
print(f'd = {d}')

e = a[::2]
print(f'e = {e}')

f = a[1::2][::-1]
print(f'f = {f}')

a = [ 1  2  3  4  5  6  7  8  9 10]
b = [2 4 6 8]
b = [ 6  7  8  9 10]
c = [ 7  8  9 10]
d = [1 2 3]
e = [1 3 5 7 9]
f = [10  8  6  4  2]


# Lab 8.

In [72]:
# 1.
a = np.arange(24).reshape(4, 3, 2)

print('index    element')
for x in range(4):
    for y in range(3):
        for z in range(2):
            print(f'{x, y, z}  {a[x][y][z]}')

index    element
(0, 0, 0)  0
(0, 0, 1)  1
(0, 1, 0)  2
(0, 1, 1)  3
(0, 2, 0)  4
(0, 2, 1)  5
(1, 0, 0)  6
(1, 0, 1)  7
(1, 1, 0)  8
(1, 1, 1)  9
(1, 2, 0)  10
(1, 2, 1)  11
(2, 0, 0)  12
(2, 0, 1)  13
(2, 1, 0)  14
(2, 1, 1)  15
(2, 2, 0)  16
(2, 2, 1)  17
(3, 0, 0)  18
(3, 0, 1)  19
(3, 1, 0)  20
(3, 1, 1)  21
(3, 2, 0)  22
(3, 2, 1)  23


In [77]:
# 2.
print(np.concatenate((a[0, 0], a[1, 0]), axis=0))
print(np.concatenate((a[0, 0], a[2, 1]), axis=0))
print(np.concatenate((a[0], a[1]), axis=0))
print(np.concatenate((a[0], a[1]), axis=1))

[0 1 6 7]
[ 0  1 14 15]
[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]
[[ 0  1  6  7]
 [ 2  3  8  9]
 [ 4  5 10 11]]


# Lab 9.

In [88]:
# 1.
a = np.arange(16).reshape(4, 4)
b = a[:, 1]
print(f'b = {b}')

c = a[2, 1:]
print(f'c = {c}')

d = a[:2, :2]
print(f'd = {d}')

e = a[1:3, 1:3]
print(f'e = {e}')

b = [ 1  5  9 13]
c = [ 9 10 11]
d = [[0 1]
 [4 5]]
e = [[ 5  6]
 [ 9 10]]


In [94]:
# 2.
f = a[:2, :3].flatten()
print(f'f = {f}')

g = a[2:, ].flatten()
print(f'g = {g}')

h = a[(1, 3), 1:].flatten()
print(f'h = {h}')

f = [0 1 2 4 5 6]
g = [ 8  9 10 11 12 13 14 15]
h = [ 5  6  7 13 14 15]


# Lab 10.

In [119]:
# 1.
a = np.array([[1, 1, -1], [2, -1, 3], [1, 2, 1]])
b = np.array([0, 9, 8])

x, y, z = np.linalg.solve(a, b)
print(f'x = {x}, y = {y}, z = {z}')

# 2.
A = np.array([[1, 1, -1], [2, -1, 3], [1, 2, 1]], dtype='int32')
print(f'det(A) = {np.linalg.det(A)}')

# 3.
first = 1 * np.linalg.det(A[1:, 1:])
second = -2 * np.linalg.det(A[(0, 2), 1:])
third = 1 * np.linalg.det(A[:2, 1:])

print(first + second + third)

x = 1.0, y = 2.0, z = 3.0
det(A) = -11.000000000000002
-11.0
