# Lab 8-1

In [3]:
# 1.

# IndexError
#a = [10, 20, 30]
# a[3]

# ValueError
# n = int('200%')

# TypeError
# a = 100 + '200'

TypeError: unsupported operand type(s) for +: 'int' and 'str'

# Lab 8-2

In [9]:
# 1 - 1.

try:
    10 * (30 / 0)
except ZeroDivisionError:
    print('0으로 나눌 수 없습니다')
    
# 1 - 2.
try:
    x = int(input('정수 x를 입력하세요 : '))
except ValueError:
    print('잘못된 값이 입력되었습니다.')

# 1 - 3.
try:
    import sys
    
    f = open("1234.txt")
    s = f.readline()
except FileNotFoundError:
    print('No such file')

0으로 나눌 수 없습니다
정수 x를 입력하세요 : j
잘못된 값이 입력되었습니다.
No such file


# Lab 8-3

In [12]:
# 1.
a = [1, 2, 3, 4, 5]

find_number = int(input('a의 요소를 하나 선택하시오 : '))
print(f'{find_number}은(는) {a.index(find_number + 1)}번째 요소입니다.')

a의 요소를 하나 선택하시오 : 1
1은(는) 1번째 요소입니다.


In [14]:
# 2.
a = [1, 2, 3, 4, 5]

try:
    find_number = int(input('a의 요소를 하나 선택하시오 : '))
except ValueError:
    print('오류 : 입력 값이 정수나 실수가 아님')
else:
    print(f'{find_number}은(는) {a.index(find_number + 1)}번째 요소입니다.')

a의 요소를 하나 선택하시오 : 3
3은(는) 3번째 요소입니다.


# Lab 8-4

In [15]:
# 1.
file = open("numbers.txt", "w")
file.write("100\n200\n300\n400")
file.close()

In [16]:
# 2.
content = """Buddy, you're a boy, make a big noise
Playing in the street, gonna be a big man someday
You got moud on your face, you big disgrace
Kicking your can all over the place, signin'
We will, we will rock you
We will, we will rock you"""

file = open("we_will_rock.txt", "w")
file.write(content)
file.close()

# Lab 8-5

In [19]:
# 1.
file = open("numbers.txt", "r")
content = file.read().rstrip()
print(content)
file.close()

100
200
300
400


In [21]:
# 2.
file = open("we_will_rock.txt", "r")
content = file.read().rstrip()
print(content)
file.close()

Buddy, you're a boy, make a big noise
Playing in the street, gonna be a big man someday
You got moud on your face, you big disgrace
Kicking your can all over the place, signin'
We will, we will rock you
We will, we will rock you


# Lab 8-6

In [23]:
# 1.
filename = input('입력할 파일의 이름 : ')

try:
    file = open(filename, "r")
except FileNotFoundError:
    print(f'No such file {filename}')
else:
    content = file.read()
    file.close()
    content_upper = content.upper()
    filename = filename[:-4] + '_upper.txt'
    
    new_file = open(filename, "w")
    new_file.write(content_upper)
    new_file.close()

입력할 파일의 이름 : we_will_rock.txt


In [37]:
# 2.
filename = input('파일 이름을 입력하세요 : ')

try:
    file = open(filename, "r")
except FileNotFoundError:
    print('No such file {filename}')
else:
    contents = []
    line = file.readline().rstrip()
    while line:
        contents.append(line)
        line = file.readline().rstrip()
        
    contents = contents[::-1]
    
    for content in contents:
        print(content)
    
    file.close()

파일 이름을 입력하세요 : we_will_rock.txt
We will, we will rock you
We will, we will rock you
Kicking your can all over the place, signin'
You got moud on your face, you big disgrace
Playing in the street, gonna be a big man someday
Buddy, you're a boy, make a big noise


# Lab 9-1

In [43]:
# 1.
print((200).__sub__(100))
print((200).__mul__(100))
print((200).__truediv__(100))

# 2.
print([10, 20, 30, 40].pop())

# 4.
print(dir(int))
print(dir(list))

100
20000
2.0
40
['__abs__', '__add__', '__and__', '__bool__', '__ceil__', '__class__', '__delattr__', '__dir__', '__divmod__', '__doc__', '__eq__', '__float__', '__floor__', '__floordiv__', '__format__', '__ge__', '__getattribute__', '__getnewargs__', '__gt__', '__hash__', '__index__', '__init__', '__init_subclass__', '__int__', '__invert__', '__le__', '__lshift__', '__lt__', '__mod__', '__mul__', '__ne__', '__neg__', '__new__', '__or__', '__pos__', '__pow__', '__radd__', '__rand__', '__rdivmod__', '__reduce__', '__reduce_ex__', '__repr__', '__rfloordiv__', '__rlshift__', '__rmod__', '__rmul__', '__ror__', '__round__', '__rpow__', '__rrshift__', '__rshift__', '__rsub__', '__rtruediv__', '__rxor__', '__setattr__', '__sizeof__', '__str__', '__sub__', '__subclasshook__', '__truediv__', '__trunc__', '__xor__', 'as_integer_ratio', 'bit_length', 'conjugate', 'denominator', 'from_bytes', 'imag', 'numerator', 'real', 'to_bytes']
['__add__', '__class__', '__contains__', '__delattr__', '__delit

# Lab 9-4

In [46]:
class Dog:
    def bark(self):
        print('멍멍~~')
        
dog = Dog()
dog.bark()

멍멍~~


In [50]:
class Dog:
    def __init__(self, name):
        self.name = name
        
    def bark(self):
        print("멍멍~~")
        
        
dog = Dog("Jindo")
dog.bark()

멍멍~~


In [52]:
class Dog:
    def __init__(self, name):
        self.name = name
        
    def bark(self):
        print("멍멍~")
        
    def __str__(self):
        return f"Dog(name = {self.name})"
    
dog = Dog("Jindo")
print(dog)

Dog(name = Jindo)


# Lab 9-7

In [53]:
n = 100
m = 100

if n is m:
    print('same')
else:
    print('no')

same


# Lab 9-8.

In [56]:
# 1.
class vector_2d():
    def __init__(self, x, y):
        self.x = x
        self.y = y

    def __str__(self):
        return f'vector pos : ({self.x}, {self.y})'
        
    def __truediv__(self, other):
        return vector_2d(self.x / other.x, self.y / other.y)
    
    def __mul__(self, other):
        return vector_2d(self.x * other.x, self.y * other.y)
    
vec1 = vector_2d(30, 40)
vec2 = vector_2d(10, 20)

print(vec1 * vec2)
print(vec1 / vec2)

vector pos : (300, 800)
vector pos : (3.0, 2.0)


In [58]:
# 2.
class vector_2d():
    def __init__(self, x, y):
        self.x = x
        self.y = y

    def __str__(self):
        if self.x > 0 and self.y > 0:
            return f'vector pos : ({self.x}, {self.y})'
        elif self.x < 0 and self.y < 0:
            return f'-vector pos : ({self.x}, {self.y})'
        
    def __truediv__(self, other):
        return vector_2d(self.x / other.x, self.y / other.y)
    
    def __mul__(self, other):
        return vector_2d(self.x * other.x, self.y * other.y)
    
    def __neg__(self):
        return vector_2d(-self.x, -self.y)
    
vec1 = vector_2d(30, 40)
vec2 = vector_2d(10, 20)

print(-vec1)

-vector pos : (-30, -40)


# Lab 9-9.

In [60]:
class vector:
    def __init__(self, x, y):
        self.x = x
        self.y = y
        
    def __gt__(self, other):
        return self.x > other.x
    
    def __ge__(self, other):
        return self.x >= other.x
    
    def __lt__(self, other):
        return self.x < other.x
    
    def __le__(self, other):
        return self.x <= other.x
    
    def __str__(self):
        return f'vector pos : ({self.x}, {self.y})'
    
    
v1 = vector(30, 40)
v2 = vector(10, 20)

print(f'v1 > v2 = {v1 > v2}')
print(f'v1 >= v2 = {v2 >= v2}')
print(f'v1 < v2 = {v1 < v2}')
print(f'v1 <= v2 = {v1 <= v2}')

v1 > v2 = True
v1 >= v2 = True
v1 < v2 = False
v1 <= v2 = False


# Lab 9-10.

In [61]:
# 1.
class Rect:
    def __init__(self, width, height):
        self.width = width
        self.height = height
        
r1 = Rect(100, 200)
print(r1.__dict__)
print(r1.__dict__['width'])

{'width': 100, 'height': 200}
100


In [62]:
# 2.
class Rect:
    def __init__(self, width, height):
        self.__width = width
        self.__height = height
        
r1 = Rect(100, 200)
print(r1.__dict__)
print(r1.__dict__['_Rect__width'])

{'_Rect__width': 100, '_Rect__height': 200}
100


# Lab 10-1

In [63]:
# 1.
# 생략

# 2.
sub = lambda x, y : x - y
print(sub(200, 100))

100


# Lab 10-2

In [66]:
# 1.
n_list = [i for i in range(1, 11)]

even_list = []
for i in filter(lambda x : x % 2 == 0, n_list):
    even_list.append(i)
    
print(even_list)

# 2.
n_list = [i for i in range(1, 11)]

odd_list = []

for i in filter(lambda x : x % 2, n_list):
    odd_list.append(i)
    
print(odd_list)

[2, 4, 6, 8, 10]
[1, 3, 5, 7, 9]


# Lab 10-3

In [67]:
# 1.
a_list = ['a', 'b', 'c', 'd']

upper_a_list = list(map(lambda x : x.upper(), a_list))
print(upper_a_list)

['A', 'B', 'C', 'D']


In [68]:
# 2.
n_list = [10, 20, 30]

twice = list(map(lambda x : x * 2, n_list))
triple = list(map(lambda x : x * 3, n_list))

print(twice)
print(triple)

[20, 40, 60]
[30, 60, 90]


# Lab 10-4

In [70]:
# 1.
from functools import reduce

numbers = [i for i in range(1, 101)]

print(f'1에서 100까지의 합 : {reduce(lambda x, y : x + y, numbers)}')

1에서 100까지의 합 : 5050


In [71]:
# 2.
from functools import reduce

print(f'10! = {reduce(lambda x, y : x * y, [i for i in range(1, 11)])}')

10! = 3628800


# Lab 10-6

In [74]:
# 1.
cubic = [i ** 3 for i in range(1, 11) if i ** 3 < 500]
print(cubic)

# 2.
st = "Hello 1234 Python"
digit = [c for c in st if c.isdigit()]
print(digit)

[1, 8, 27, 64, 125, 216, 343]
['1', '2', '3', '4']


# Lab 11-1

In [78]:
# 1.
import numpy as np

a = np.array([i for i in range(10)])
print(a)

# 4.
print(a.shape)
print(a.ndim)
print(a.dtype)
print(a.size)
print(a.itemsize)

[0 1 2 3 4 5 6 7 8 9]
(10,)
1
int32
10
4


# Lab 11-2

In [88]:
# 1.
sample = [23, 45, 67, 7, 2, 30, 34, 82]
a = np.array(sample)

print(f'최댓값 : {a.max()}')
print(f'최솟값 : {a.min()}')
print(f'평균값 : {a.mean()}')

# 2.
b = np.random.randint(0, 99, size = 10)
print(f'최댓값 : {b.max()}')
print(f'최솟값 : {b.min()}')
print(f'평균값 : {b.mean()}')

# 3.
np.append(a, b)
c = np.array(a)
c.flatten()
print(c)

최댓값 : 82
최솟값 : 2
평균값 : 36.25
최댓값 : 88
최솟값 : 2
평균값 : 38.6
[23 45 67  7  2 30 34 82]


# Lab 11-3

In [90]:
# 1.
A = np.array([i for i in range(1, 10)]).reshape(3, 3)
B = np.array([2 for _ in range(9)]).reshape(3, 3)

print(A)
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[2 2 2]
 [2 2 2]
 [2 2 2]]


In [92]:
# 2.
print(A + B)
print(A - B)
print(A * B)
print(A / B)
print(A @ B)
print(A ** 2)

[[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[-1  0  1]
 [ 2  3  4]
 [ 5  6  7]]
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
[[0.5 1.  1.5]
 [2.  2.5 3. ]
 [3.5 4.  4.5]]
[[12 12 12]
 [30 30 30]
 [48 48 48]]
[[ 1  4  9]
 [16 25 36]
 [49 64 81]]


# Lab 11-4

In [97]:
# 1.
a1 = np.full((3, 3), 2)
print(a1)

# 2.
a2 = np.array([i for i in range(1, 13)])
print(a2)

# 3.
a3 = np.array([i for i in range(3, 50, 3)])
print(a3)

# 4.
a4 = np.linspace(0, 20, 5)
print(a4)

[[2 2 2]
 [2 2 2]
 [2 2 2]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]
[ 3  6  9 12 15 18 21 24 27 30 33 36 39 42 45 48]
[ 0.  5. 10. 15. 20.]


# Lab 11-5

In [99]:
# 1.
a1 = np.array([i for i in range(1, 13)])
a1 = a1.reshape(2, 6)
print(a1)

# 2.
a2 = np.array([i for i in range(1, 31)])
a2 = a2.reshape(3, 10)
print(a2)

# 3.
a3 = a2.reshape(6, 5)
print(a3)

# 4.
a4 = np.transpose(a3)
print(a4)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]
[[ 1  6 11 16 21 26]
 [ 2  7 12 17 22 27]
 [ 3  8 13 18 23 28]
 [ 4  9 14 19 24 29]
 [ 5 10 15 20 25 30]]


# Lab 11-6

In [108]:
# 1.
a = np.random.randint(1, 100, size = 15)
a = a.reshape(3, 5)
print(a)

# 2.
print(f'a의 열방향 최댓값 : {a.max(axis = 0)}')
print(f'a의 열방향 최솟값 : {a.min(axis = 0)}')
print(f'a의 열방향 평균 : {a.mean(axis = 0)}')

# 3.
print(f'a의 행방향 최댓값 : {a.max(axis = 1)}')
print(f'a의 행방향 최솟값 : {a.min(axis = 1)}')
print(f'a의 행방향 평균 : {a.mean(axis = 1)}')

[[73 37  4 63 76]
 [32 46 57 11 43]
 [90 54 13 39 90]]
a의 열방향 최댓값 : [90 54 57 63 90]
a의 열방향 최솟값 : [32 37  4 11 43]
a의 열방향 평균 : [65.         45.66666667 24.66666667 37.66666667 69.66666667]
a의 행방향 최댓값 : [76 57 90]
a의 행방향 최솟값 : [ 4 11 13]
a의 행방향 평균 : [50.6 37.8 57.2]


# Lab 11-7

In [117]:
# 1.
a = np.array([i for i in range(1, 11)])
b = a[1:-1:2]
print(b)

# 2.
b = a[5:]
print(b)

c = a[6:]
print(c)

d = a[:3]
print(d)

e = a[0::2]
print(e)

f = a[-1::-2]
print(f)

[2 4 6 8]
[ 6  7  8  9 10]
[ 7  8  9 10]
[1 2 3]
[1 3 5 7 9]
[10  8  6  4  2]


# Lab 11-8

In [118]:
# 1.
a = np.array([i for i in range(24)]).reshape(4, 3, 2)
print(a)

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]

 [[18 19]
  [20 21]
  [22 23]]]


In [129]:
# 2.
a1 = np.concatenate((a[0][0], a[1][0]), axis=0)
print(a1)

a2 = np.concatenate((a[0][0], a[2][1]), axis=0)
print(a2)

a3 = np.concatenate((a[0], a[1]), axis=0)
print(a3)

a4 = np.concatenate((a[0], a[1]), axis=1)
print(a4)

[0 1 6 7]
[ 0  1 14 15]
[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]
[[ 0  1  6  7]
 [ 2  3  8  9]
 [ 4  5 10 11]]


# Lab 11-9

In [137]:
# 1.
a = np.array([i for i in range(16)]).reshape(4, 4)

b = a[:, 1]
print(b)

c = a[2, 1:]
print(c)

d = a[:2, :2]
print(d)

e = a[1:3, 1:3]
print(e)

[ 1  5  9 13]
[ 9 10 11]
[[0 1]
 [4 5]]
[[ 5  6]
 [ 9 10]]


In [139]:
# 2.
f = a[:2, :3].flatten()
print(f)

g = a[2:, :].flatten()
print(g)

h = a[1::2, 1:].flatten()
print(h)

[0 1 2 4 5 6]
[ 8  9 10 11 12 13 14 15]
[ 5  6  7 13 14 15]


# Lab 11-10

In [144]:
# 1. 
A = np.array([
    [1, 1, -1],
    [2, -1, 3],
    [1, 2, 1]
])

B = np.array([
    [0],
    [9],
    [8]
])

sols = np.linalg.solve(A, B)

print(f'x = {sols[0][0]}, y = {sols[1][0]}, z = {sols[2][0]}')

# 2.
detA = np.linalg.det(A)
print(f'det(A) = {detA}')

x = 1.0, y = 2.0, z = 3.0
det(A) = -11.000000000000002
